import { Ride } from "app/models/Ride";

export const rides = [
  {
      "id": 1,
      "type": "PRIVATFAHRT",
      "from": "Munich",
      "to": "Geneva",
      "offeredBy": {
          "id": 1,
          "email": "benedikt@rossgardt.de",
          "password": "none",
          "firstname": "Benedikt",
          "lastname": "Rossgardt",
          "img": "profile.jpg",
          "userRating": 4.3,
          "language": "de_DE"
      },
      "stops": [],
      "travelDay": "2018-08-30 00:08:00",
      "arrivalTime": "2018-08-30 20:00:00",
      "return": false,
      "freeSeating": true,
      "seats": "3",
      "price": "40.00",
      "departureLocation": "Muenchen Hauptbahnhof",
      "description": "Herzlich willkommen bei der Fahrt!",
      "pet": true,
      "twoseats": true,
      "woman": false,
      "smoker": false,
      "baggageSize": "M",
      "detour": "0",
      "agbAgreed": true,
      "dataPrivacyAgreed": true,
      "immediateBooking": true,
      "payment": "BAR",
      "passengerSeatReserved": null,
      "backSeatLeftReserved": null,
      "backSeatRightReserved": null,
      "backSeatMiddleReserved": null,
      "thirdRowLeftReserved": null,
      "thirdRowRightReserved": null,
      "thirdRowMiddleReserved": null
  },
  {
      "id": 2,
      "type": "PRIVATFAHRT",
      "from": "Munich",
      "to": "Prague",
      "offeredBy": {
          "id": 1,
          "email": "benedikt@rossgardt.de",
          "password": "none",
          "firstname": "Benedikt",
          "lastname": "Rossgardt",
          "img": "profile.jpg",
          "userRating": 4.3,
          "language": "de_DE"
      },
      "stops": [],
      "travelDay": "2018-08-31 00:12:00",
      "arrivalTime": "2018-08-30 18:00:00",
      "return": false,
      "freeSeating": true,
      "seats": "3",
      "price": "20.00",
      "departureLocation": "Muenchen Hauptbahnhof",
      "description": "Herzlich willkommen bei der Fahrt!",
      "pet": true,
      "twoseats": true,
      "woman": false,
      "smoker": false,
      "baggageSize": "M",
      "detour": "0",
      "agbAgreed": true,
      "dataPrivacyAgreed": true,
      "immediateBooking": true,
      "payment": "BAR",
      "passengerSeatReserved": null,
      "backSeatLeftReserved": null,
      "backSeatRightReserved": null,
      "backSeatMiddleReserved": null,
      "thirdRowLeftReserved": null,
      "thirdRowRightReserved": null,
      "thirdRowMiddleReserved": null
  },
  {
      "id": 3,
      "type": "PRIVATFAHRT",
      "from": "Hamburg",
      "to": "Munich",
      "offeredBy": {
          "id": 1,
          "email": "benedikt@rossgardt.de",
          "password": "none",
          "firstname": "Benedikt",
          "lastname": "Rossgardt",
          "img": "profile.jpg",
          "userRating": 4.3,
          "language": "de_DE"
      },
      "stops": [],
      "travelDay": "2018-08-28 00:12:00",
      "arrivalTime": "2018-08-30 18:00:00",
      "return": false,
      "freeSeating": true,
      "seats": "3",
      "price": "30.00",
      "departureLocation": "Muenchen Hauptbahnhof",
      "description": "Herzlich willkommen bei der Fahrt!",
      "pet": true,
      "twoseats": true,
      "woman": false,
      "smoker": false,
      "baggageSize": "M",
      "detour": "0",
      "agbAgreed": true,
      "dataPrivacyAgreed": true,
      "immediateBooking": true,
      "payment": "BAR",
      "passengerSeatReserved": null,
      "backSeatLeftReserved": null,
      "backSeatRightReserved": null,
      "backSeatMiddleReserved": null,
      "thirdRowLeftReserved": null,
      "thirdRowRightReserved": null,
      "thirdRowMiddleReserved": null
  }
];

export const getRandomRide = (): Array<Ride>|null => {
  const returnEmpty: boolean = (Math.floor(Math.random()+.5)===0) ? false : true;
  return (returnEmpty) ? [] : [<any>rides[Math.floor(Math.random()*rides.length+.5)]];
}
